module.exports = {
  theme: {
    colors: {
      transparent: "transparent",
      
      "green-darkest": "#1B3324",
      "green-darker": "#325B3E",
      "green-dark": "#478057",
      green: "#5FB881",
      "green-light": "#84C697",
      "green-lighter": "#a2f5bf",
      "green-lightest": "#F4F7F5",
      
      black: "#22292f",
      "grey-darkest": "#1A1A1A",
      "grey-darker": "#202020",
      "grey-dark": "#2E2E2E",
      grey: "#424242",
      "grey-light": "#676767",
      "grey-lighter": "#8D8D8D",
      "grey-lightest": "#DCDCDC",
      "grey-faint": "#F7F7F7",
      white: "#ffffff",
      
      "orange-darkest": "#462a16",
      "orange-darker": "#613b1f",
      "orange-dark": "#de751f",
      orange: "#f6993f",
      "orange-light": "#faad63",
      "orange-lighter": "#fcd9b6",
      "orange-lightest": "#fff5eb",
      
      "red-darkest": "#3b0d0c",
      "red-darker": "#621b18",
      "red-dark": "#cc1f1a",
      red: "#e3342f",
      "red-light": "#ef5753",
      "red-lighter": "#f9acaa",
      "red-lightest": "#fcebea",
      
      "slate-darkest": "#212C30",
      "slate-darker": "#29363C",
      "slate-dark": "#3A4C55",
      slate: "#546E7A",
      "slate-light": "#768B94",
      "slate-lighter": "#98A8AF",
      "slate-lightest": "#E9EDF1",
      
      "brown-darkest": "#30221C",
      "brown-darker": "#3C2A23",
      "brown-dark": "#543B32",
      brown: "#795548",
      "brown-light": "#93776C",
      "brown-lighter": "#AE9991",
      "brown-lightest": "#E6E0DD",
      
      "blue-darkest": "#1A4262",
      "blue-darker": "#20527A",
      "blue-dark": "#2E73AB",
      blue: "#42A5F5",
      "blue-light": "#67B7F7",
      "blue-lighter": "#bcdefa",
      "blue-lightest": "#DCEEFD",
      
      "indigo-darkest": "#242A4C",
      "indigo-darker": "#2D355F",
      "indigo-dark": "#404A86",
      indigo: "#5C6BC0",
      "indigo-light": "#7C88CC",
      "indigo-lighter": "#9DA6D9",
      "indigo-lightest": "#E1E4F3",
      
      "purple-darkest": "#32224D",
      "purple-darker": "#3E2B60",
      "purple-dark": "#573C87",
      purple: "#7E57C2",
      "purple-light": "#9778CE",
      "purple-lighter": "#B19ADA",
      "purple-lightest": "#E7E0F3",
      
      "pink-darkest": "#60273A",
      "pink-darker": "#773048",
      "pink-dark": "#CF2B66",
      pink: "#F06292",
      "pink-light": "#F381A7",
      "pink-lighter": "#F6A0BD",
      "pink-lightest": "#FCE2EB"
    },
    screens: {
      sm: "576px",
      md: "768px",
      lg: "992px",
      xl: "1200px",
      xxl: "1500px"
    },
    fontFamily: {
      sans: [
        "system-ui",
        "BlinkMacSystemFont",
        "-apple-system",
        "Segoe UI",
        "Roboto",
        "Oxygen",
        "Ubuntu",
        "Cantarell",
        "Fira Sans",
        "Droid Sans",
        "Helvetica Neue",
        "sans-serif"
      ],
      serif: [
        "Constantia",
        "Lucida Bright",
        "Lucidabright",
        "Lucida Serif",
        "Lucida",
        "DejaVu Serif",
        "Bitstream Vera Serif",
        "Liberation Serif",
        "Georgia",
        "serif"
      ],
      mono: [
        "Menlo",
        "Monaco",
        "Consolas",
        "Liberation Mono",
        "Courier New",
        "monospace"
      ],
      cafe: ["Louis George Cafe Bold"]
    },
    fontSize: {
      "12": "1.2rem",
      "14": "1.4rem",
      "16": "1.6rem",
      "18": "1.8rem",
      "20": "2rem",
      "24": "2.4rem",
      "30": "3rem",
      "36": "3.6rem",
      "48": "4.8rem",
      "60": "6rem",
      "72": "7.2rem"
    },
    fontWeight: {
      hairline: 100,
      thin: 200,
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
      black: 900
    },
    lineHeight: {
      none: 1,
      tight: 1.25,
      normal: 1.5,
      relaxed: 1.625,
      loose: 2
    },
    letterSpacing: {
      tight: "-0.025em",
      normal: "0",
      wide: "0.05em"
    },
    textColor: theme => theme('colors'),
    backgroundColor: theme => theme('colors'),
    backgroundSize: {
      auto: "auto",
      cover: "cover",
      contain: "contain"
    },
    borderWidth: {
      default: "1px",
      "0": "0",
      "2": "2px",
      "4": "4px",
      "8": "8px",
      "10": "1rem",
      "20": "2rem"
    },
    borderColor: theme => ({
      default: theme('colors.grey-light'),
      ...theme('colors'),
    }),
    borderRadius: {
      none: "0",
      sm: ".125rem",
      default: ".25rem",
      lg: ".5rem",
      full: "9999px"
    },
    width: {
      auto: "auto",
      "10": "1rem",
      "15": "1.5rem",
      "20": "2rem",
      "30": "3rem",
      "35": "3.5rem",
      "40": "4rem",
      "50": "5rem",
      "60": "6rem",
      "70": "7rem",
      "75": "7.5rem",
      "80": "8rem",
      "90": "9rem",
      "100": "10rem",
      "110": "11rem",
      "150": "15rem",
      "200": "20rem",
      "250": "25rem",
      "300": "30rem",
      "315": "31.5rem",
      "350": "35rem",
      "575": "57.5rem",
      "720": "72rem",
      "1/2": "50%",
      "1/3": "33.33333%",
      "2/3": "66.66667%",
      "1/4": "25%",
      "3/4": "75%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
      "1/6": "16.66667%",
      "5/6": "83.33333%",
      full: "100%",
      screen: "100vw"
    },
    height: {
      auto: "auto",
      "3": ".3rem",
      "10": "1rem",
      "15": "1.5rem",
      "20": "2rem",
      "30": "3rem",
      "35": "3.5rem",
      "40": "4rem",
      "42": "4.2rem",
      "48": "4.8rem",
      "50": "5rem",
      "60": "6rem",
      "70": "7rem",
      "75": "7.5rem",
      "80": "8rem",
      "90": "9rem",
      "100": "10rem",
      "110": "11rem",
      "150": "15rem",
      "175": "17.5rem",
      "315": "31.5rem",
      "350": "35rem",
      "400": "40rem",
      "500": "50rem",
      "600": "60rem",
      "700": "70rem",
      full: "100%",
      screen: "100vh"
    },
    minWidth: {
      "0": "0",
      "10": "1rem",
      "15": "1.5rem",
      "20": "2rem",
      "30": "3rem",
      "40": "4rem",
      "50": "5rem",
      "60": "6rem",
      "80": "8rem",
      "100": "10rem",
      "150": "15rem",
      "200": "20rem",
      "300": "30rem",
      full: "100%"
    },
    minHeight: {
      "0": "0",
      "10": "1rem",
      "15": "1.5rem",
      "20": "2rem",
      "30": "3rem",
      "40": "4rem",
      "50": "5rem",
      "60": "6rem",
      "80": "8rem",
      "100": "10rem",
      "120": "12rem",
      "160": "16rem",
      "221": "22.1rem",
      full: "100%",
      screen: "100vh",
      "half-screen": "50vh"
    },
    maxWidth: {
      "10": "1rem",
      "15": "1.5rem",
      "20": "2rem",
      "30": "3rem",
      "40": "4rem",
      "50": "5rem",
      "60": "6rem",
      "80": "8rem",
      "100": "10rem",
      "400": "40rem",
      "500": "50rem",
      "600": "60rem",
      "800": "80rem",
      "1000": "100rem",
      full: "100%"
    },
    maxHeight: {
      "10": "1rem",
      "15": "1.5rem",
      "20": "2rem",
      "30": "3rem",
      "40": "4rem",
      "50": "5rem",
      "60": "6rem",
      "80": "8rem",
      "100": "10rem",
      full: "100%",
      screen: "100vh"
    },
    padding: {
      "0": "0",
      "5": ".5rem",
      "10": "1rem",
      "12": "1.2rem",
      "15": "1.5rem",
      "20": "2rem",
      "30": "3rem",
      "40": "4rem",
      "50": "5rem",
      "60": "6rem",
      "80": "8rem",
      "100": "10rem",
      "110": "11rem",
      "150": "15rem"
    },
    margin: {
      auto: "auto",
      "0": "0",
      "5": ".5rem",
      "10": "1rem",
      "15": "1.5rem",
      "20": "2rem",
      "30": "3rem",
      "37": "3.7rem",
      "40": "4rem",
      "50": "5rem",
      "60": "6rem",
      "80": "8rem",
      "100": "10rem",
      "120": "12rem",
      "150": "15rem",
      "-px": "-1px",
      "-5": "-.5rem",
      "-10": "-1rem",
      "-14": "-1.4rem",
      "-20": "-2rem",
      "-30": "-3rem",
      "-40": "-4rem",
      "-50": "-5rem",
      "-60": "-6rem",
      "-80": "-8rem",
      "-100": "-10rem"
    },
    boxShadow: {
      default: "0 2px 4px 0 rgba(0,0,0,0.10)",
      md: "0 4px 8px 0 rgba(0,0,0,0.08), 0 2px 4px 0 rgba(0,0,0,0.05)",
      lg: "0 15px 30px 0 rgba(0,0,0,0.08), 0 5px 15px 0 rgba(0,0,0,0.05)",
      inner: "inset 0 2px 4px 0 rgba(0,0,0,0.1)",
      outline: "0 0 0 3px rgba(52,144,220,0.5)",
      none: "none"
    },
    zIndex: {
      auto: "auto",
      "0": 0,
      "10": 10,
      "20": 20,
      "30": 30,
      "40": 40,
      "50": 50
    },
    fill: {
      current: "currentColor"
    },
    stroke: {
      current: "currentColor"
    },
    container: {
      center: true,
      padding: "2rem"
    }
  },
  variants: {
    appearance: ["responsive"],
    backgroundAttachment: ["responsive"],
    backgroundColor: ["responsive", "hover", "focus", "group-hover"],
    backgroundPosition: ["responsive"],
    backgroundRepeat: ["responsive"],
    backgroundSize: ["responsive"],
    borderCollapse: [],
    borderColor: ["responsive", "hover", "focus"],
    borderRadius: ["responsive"],
    borderStyle: ["responsive"],
    borderWidth: ["responsive"],
    cursor: ["responsive"],
    display: ["responsive"],
    flexDirection: ["responsive"],
    flexWrap: ["responsive"],
    alignItems: ["responsive"],
    alignSelf: ["responsive"],
    justifyContent: ["responsive"],
    alignContent: ["responsive"],
    flex: ["responsive"],
    flexGrow: ["responsive"],
    flexShrink: ["responsive"],
    float: ["responsive"],
    fontFamily: ["responsive"],
    fontWeight: ["responsive", "hover", "focus"],
    height: ["responsive"],
    lineHeight: ["responsive"],
    listStylePosition: ["responsive"],
    listStyleType: ["responsive"],
    margin: ["responsive"],
    maxHeight: ["responsive"],
    maxWidth: ["responsive"],
    minHeight: ["responsive"],
    minWidth: ["responsive"],
    negativeMargin: ["responsive"],
    opacity: ["responsive"],
    outline: ["focus"],
    overflow: ["responsive"],
    padding: ["responsive"],
    pointerEvents: ["responsive"],
    position: ["responsive"],
    inset: ["responsive"],
    resize: ["responsive"],
    boxShadow: ["responsive", "hover", "focus"],
    fill: [],
    stroke: [],
    textAlign: ["responsive"],
    textColor: ["responsive", "hover", "focus", "group-hover"],
    fontSize: ["responsive"],
    fontStyle: ["responsive", "hover", "focus"],
    fontSmoothing: ["responsive", "hover", "focus"],
    textDecoration: ["responsive", "hover", "focus"],
    textTransform: ["responsive", "hover", "focus"],
    letterSpacing: ["responsive"],
    userSelect: ["responsive"],
    verticalAlign: ["responsive"],
    visibility: ["responsive"],
    whitespace: ["responsive"],
    wordBreak: ["responsive"],
    width: ["responsive"],
    zIndex: ["responsive"]
  },
  corePlugins: {},
  plugins: []
};
